### ISSUE TITLE
python 3.6.5 incompatibility 

### ISSUE THREAD

**Issue by Yaksinikos** [alexriss/keyboard-layout-converter#1]
Looks like is is no longer working, as using python 3.6.5 it shows some issues;
```
./convert_to_xkb.py: line 5: str_linux_win: command not found.
./convert_to_xkb.py: line 61: syntax issue on expression `('
./convert_to_xkb.py: line 61: `output = open("language.xkb","w")'
```

**Comment by alexriss** [comment]
works for me still. 

I can't make much sense  from your error messages. str_linux_win is a variable assignment, should not be a command. Are you sure you are running this with a python interpreter? It looks a bit like you are running it from bash or something like that.

**Comment by Yaksinikos** [comment]
... every time I forget this * python interpreter ....
